"""DORA-V2-002A — the ORM models and migration 026 describe the same two tables.

What:  runs Alembic's metadata comparison against the live database, scoped to
       dora_contracts and dora_contract_parties on both the model side and the
       reflected side, with type and server-default comparison switched on,
       and asserts it finds nothing. Proves the scope is not what makes it pass
       (dropping either table from the metadata is noticed) and that the
       server-default flag is honoured (a mutated default is noticed). Then
       verifies what the comparison cannot see, on both sides: every CHECK
       expression (catalog text and model text), the primary keys, every
       foreign key and unique constraint by exact definition, the one plain
       index, and the column defaults.
Why:   A future autogenerated revision must not propose "fixing" the database
       to match a drifted model. The historical tables carry known drift that
       is not this ticket's to fix, hence the scope; the V2-001 tables have
       their own parity test.
How:   pytest tests/integration/test_dora_v2_002a_schema_parity.py -m integration -v
"""

from __future__ import annotations

import os

import pytest
from sqlalchemy import (
    CheckConstraint,
    DefaultClause,
    ForeignKeyConstraint,
    MetaData,
    UniqueConstraint,
    create_engine,
    text,
)

from config.constants import CONTRACT_REFERENCE_MAX_CHARACTERS
from src.models import Base
from src.models.dora_contract import CONTRACT_TEXT_TRIM_CHARACTERS, DORAContract
from src.models.dora_contract_party import DORAContractParty
from src.models.dora_organization import DORAOrganization
from src.models.tenant import Tenant

# Tenant and DORAOrganization are imported so the metadata can resolve the
# foreign keys the two tables declare; the scope hooks exclude both tables
# from the comparison itself.

_MODELS = (DORAContract, DORAContractParty)
_SCOPE = frozenset(model.__tablename__ for model in _MODELS)

# pg_get_constraintdef() prints the trim set as a plain literal of the
# characters themselves, so the expected text is built from the service
# constant: a CHECK trimming any other set cannot match it.
_CATALOG_TRIM_LITERAL = f"'{CONTRACT_TEXT_TRIM_CHARACTERS}'::text"

_EXPECTED_CHECKS = {
    "ck_dora_contracts_reference_canonical":
        f"CHECK (((contract_reference = btrim(contract_reference, {_CATALOG_TRIM_LITERAL})) "
        "AND (contract_reference <> ''::text)))",
    "ck_dora_contracts_display_name_canonical":
        f"CHECK (((display_name IS NULL) OR ((display_name = btrim(display_name, {_CATALOG_TRIM_LITERAL})) "
        "AND (display_name <> ''::text))))",
    "ck_dora_contracts_reference_length":
        f"CHECK ((char_length(contract_reference) <= {CONTRACT_REFERENCE_MAX_CHARACTERS}))",
    "ck_dora_contracts_date_order":
        "CHECK (((contract_start_date IS NULL) OR (contract_end_date IS NULL) "
        "OR (contract_end_date >= contract_start_date)))",
    "ck_dora_contract_parties_party_role":
        "CHECK (((party_role)::text = ANY ((ARRAY['recipient_signatory'::character varying, "
        "'provider_signatory'::character varying, 'intragroup_provider_signatory'::character varying])::text[])))",
}

# The same CHECKs as the models declare them, in source form. Alembic never
# compares CHECK expressions, so without this a model CHECK could drift from
# migration 026 with every other test green. The trim literal is rebuilt from
# the service constant as the \uXXXX escapes the model writes.
_MODEL_TRIM_LITERAL = "E'" + "".join(f"\\u{ord(ch):04x}" for ch in CONTRACT_TEXT_TRIM_CHARACTERS) + "'"

_EXPECTED_MODEL_CHECKS = {
    "ck_dora_contracts_reference_canonical":
        f"contract_reference = btrim(contract_reference, {_MODEL_TRIM_LITERAL}) AND contract_reference <> ''",
    "ck_dora_contracts_reference_length":
        f"char_length(contract_reference) <= {CONTRACT_REFERENCE_MAX_CHARACTERS}",
    "ck_dora_contracts_display_name_canonical":
        f"display_name IS NULL OR (display_name = btrim(display_name, {_MODEL_TRIM_LITERAL}) "
        "AND display_name <> '')",
    "ck_dora_contracts_date_order":
        "contract_start_date IS NULL OR contract_end_date IS NULL OR contract_end_date >= contract_start_date",
    "ck_dora_contract_parties_party_role":
        "party_role IN ('recipient_signatory', 'provider_signatory', 'intragroup_provider_signatory')",
}

_EXPECTED_PRIMARY_KEYS = {
    "dora_contracts_pkey": "PRIMARY KEY (contract_id)",
    "dora_contract_parties_pkey": "PRIMARY KEY (contract_party_id)",
}

_EXPECTED_FOREIGN_KEYS = {
    "dora_contracts_tenant_id_fkey": "FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id)",
    "dora_contract_parties_tenant_id_fkey": "FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id)",
    "fk_dora_contract_parties_contract":
        "FOREIGN KEY (tenant_id, contract_id) REFERENCES dora_contracts(tenant_id, contract_id)",
    "fk_dora_contract_parties_organization":
        "FOREIGN KEY (tenant_id, organization_id) REFERENCES dora_organizations(tenant_id, organization_id)",
}

_EXPECTED_UNIQUES = {
    "uq_dora_contracts_tenant_contract": "UNIQUE (tenant_id, contract_id)",
    "uq_dora_contracts_tenant_reference": "UNIQUE (tenant_id, contract_reference)",
    "uq_dora_contract_parties_tenant_tuple": "UNIQUE (tenant_id, contract_id, organization_id, party_role)",
}

_EXPECTED_PLAIN_INDEXES = {
    "ix_dora_contract_parties_tenant_org_contract":
        "CREATE INDEX ix_dora_contract_parties_tenant_org_contract "
        "ON public.dora_contract_parties USING btree (tenant_id, organization_id, contract_id)",
}

_EXPECTED_COLUMN_DEFAULTS = {
    ("dora_contracts", "contract_id"): "gen_random_uuid()",
    ("dora_contracts", "is_active"): "true",
    ("dora_contracts", "created_at"): "now()",
    ("dora_contracts", "updated_at"): "now()",
    ("dora_contract_parties", "contract_party_id"): "gen_random_uuid()",
    ("dora_contract_parties", "is_active"): "true",
    ("dora_contract_parties", "created_at"): "now()",
    ("dora_contract_parties", "updated_at"): "now()",
}

_CONSTRAINT_DEFS_SQL = """
SELECT con.conname, pg_get_constraintdef(con.oid)
FROM pg_constraint con
JOIN pg_class rel ON rel.oid = con.conrelid
JOIN pg_namespace ns ON ns.oid = rel.relnamespace
WHERE ns.nspname = 'public' AND rel.relname = %s AND con.contype = %s
"""

_INDEX_DEFS_SQL = """
SELECT indexname, indexdef FROM pg_indexes
WHERE schemaname = 'public' AND tablename = %s AND indexname NOT LIKE '%%_pkey'
"""

_COLUMN_DEFAULTS_SQL = """
SELECT table_name, column_name, column_default FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = %s AND column_default IS NOT NULL
"""


def _in_scope_reflected(name, type_, parent_names) -> bool:
    """Alembic include_name hook: reflect only the two contract tables."""
    if type_ == "table":
        return name in _SCOPE
    return True


def _in_scope_object(obj, name, type_, reflected, compare_to) -> bool:
    """Alembic include_object hook: compare only objects belonging to the two contract tables."""
    if type_ == "table":
        return name in _SCOPE
    return True


def _scoped_metadata_diff(metadata: MetaData) -> list:
    """Run compare_metadata for the two tables only, with types and server defaults compared, flattened."""
    from alembic.autogenerate import compare_metadata
    from alembic.migration import MigrationContext

    engine = create_engine(os.environ["DATABASE_URL"])
    try:
        with engine.connect() as connection:
            migration_context = MigrationContext.configure(
                connection,
                opts={
                    "compare_type": True,
                    "compare_server_default": True,
                    "include_name": _in_scope_reflected,
                    "include_object": _in_scope_object,
                },
            )
            diffs = compare_metadata(migration_context, metadata)
    finally:
        engine.dispose()
    flat = []
    for group in diffs:
        flat.extend(group if isinstance(group, list) else [group])
    return flat


def _copy_of(*models) -> MetaData:
    """Return a fresh MetaData holding tenants, organisations and the given models, for mutation tests."""
    copied = MetaData()
    for model in (Tenant, DORAOrganization, *models):
        model.__table__.to_metadata(copied)
    return copied


def _catalog(conn, sql: str, *params) -> dict[str, str]:
    """Run a two-column (name, definition) catalog query for each of the two tables and merge the results."""
    found: dict[str, str] = {}
    for table in _SCOPE:
        with conn.transaction():
            rows = conn.execute(sql, [table, *params]).fetchall()
        for name, definition in rows:
            found[name] = definition
    return found


def _column_defaults(conn) -> dict[tuple[str, str], str]:
    """Return {(table, column): default expression} for every defaulted column of the two tables."""
    found: dict[tuple[str, str], str] = {}
    for table in _SCOPE:
        with conn.transaction():
            rows = conn.execute(_COLUMN_DEFAULTS_SQL, [table]).fetchall()
        for table_name, column_name, default in rows:
            found[(table_name, column_name)] = default
    return found


def _model_constraints(kind) -> dict[str, object]:
    """Return {name: constraint} for every named constraint of one kind across the two models."""
    found: dict[str, object] = {}
    for model in _MODELS:
        for constraint in model.__table__.constraints:
            if isinstance(constraint, kind) and constraint.name:
                found[constraint.name] = constraint
    return found


# ── Alembic's comparison, scoped, server defaults on ────────────────────────


@pytest.mark.integration
def test_alembic_finds_no_drift_between_the_models_and_the_live_tables(db_connection):
    diffs = _scoped_metadata_diff(Base.metadata)
    assert diffs == [], "autogenerate would propose: " + "; ".join(str(d)[:200] for d in diffs)


@pytest.mark.integration
@pytest.mark.parametrize("missing", _MODELS, ids=[m.__tablename__ for m in _MODELS])
def test_the_scope_filter_is_not_hiding_either_table(db_connection, missing):
    # Dropping the parent drops the party table from the copy as well (its
    # composite FK cannot resolve without it); the parent must still be noticed.
    remaining = (DORAContract,) if missing is DORAContractParty else ()
    diffs = _scoped_metadata_diff(_copy_of(*remaining))
    removed = {d[1].name for d in diffs if d[0] == "remove_table"}
    assert missing.__tablename__ in removed


@pytest.mark.integration
def test_server_default_comparison_is_actually_in_effect(db_connection):
    mutated = _copy_of(*_MODELS)
    mutated.tables["dora_contract_parties"].c.is_active.server_default = DefaultClause(text("false"))
    diffs = _scoped_metadata_diff(mutated)
    assert [(d[0], d[2], d[3]) for d in diffs] == [("modify_default", "dora_contract_parties", "is_active")]


# ── What the comparison cannot see, from the catalogs ───────────────────────


@pytest.mark.integration
def test_check_constraints_are_exactly_what_migration_026_wrote(db_connection):
    assert _catalog(db_connection, _CONSTRAINT_DEFS_SQL, "c") == _EXPECTED_CHECKS
    model_checks = {name: str(check.sqltext) for name, check in _model_constraints(CheckConstraint).items()}
    assert model_checks == _EXPECTED_MODEL_CHECKS


@pytest.mark.integration
def test_primary_keys_are_exactly_what_migration_026_wrote(db_connection):
    # Autogenerate does not compare primary keys either.
    assert _catalog(db_connection, _CONSTRAINT_DEFS_SQL, "p") == _EXPECTED_PRIMARY_KEYS
    model_keys = {
        f"{model.__tablename__}_pkey": [column.name for column in model.__table__.primary_key.columns]
        for model in _MODELS
    }
    assert model_keys == {"dora_contracts_pkey": ["contract_id"], "dora_contract_parties_pkey": ["contract_party_id"]}


@pytest.mark.integration
def test_foreign_keys_are_exactly_what_migration_026_wrote(db_connection):
    assert _catalog(db_connection, _CONSTRAINT_DEFS_SQL, "f") == _EXPECTED_FOREIGN_KEYS
    assert set(_model_constraints(ForeignKeyConstraint)) == set(_EXPECTED_FOREIGN_KEYS)


@pytest.mark.integration
def test_unique_constraints_are_exactly_what_migration_026_wrote(db_connection):
    assert _catalog(db_connection, _CONSTRAINT_DEFS_SQL, "u") == _EXPECTED_UNIQUES
    model_uniques = _model_constraints(UniqueConstraint)
    assert set(model_uniques) == set(_EXPECTED_UNIQUES)
    for name, constraint in model_uniques.items():
        columns = ", ".join(col.name for col in constraint.columns)
        assert _EXPECTED_UNIQUES[name] == f"UNIQUE ({columns})"


@pytest.mark.integration
def test_the_only_plain_index_is_the_reverse_lookup(db_connection):
    plain = {
        name: definition for name, definition in _catalog(db_connection, _INDEX_DEFS_SQL).items()
        if name not in _EXPECTED_UNIQUES
    }
    assert plain == _EXPECTED_PLAIN_INDEXES
    model_indexes = {ix.name for model in _MODELS for ix in model.__table__.indexes}
    assert model_indexes == set(_EXPECTED_PLAIN_INDEXES)


@pytest.mark.integration
def test_column_defaults_are_exactly_what_migration_026_wrote(db_connection):
    assert _column_defaults(db_connection) == _EXPECTED_COLUMN_DEFAULTS
