"""DORA-V2-002B — the ORM model and migration 027 describe the same dora_contract_relationships table.

What:  runs Alembic's metadata comparison against the live database, scoped to
       dora_contract_relationships on both the model side and the reflected
       side, with type and server-default comparison switched on, and asserts
       it finds nothing. Proves the scope is not what makes it pass (dropping
       the table from the metadata is noticed) and that the server-default
       flag is honoured (a mutated default is noticed). Then verifies from the
       catalogs, and on the model, what the comparison cannot see: both CHECK
       expressions, the primary key, every foreign key, every index definition,
       the column defaults, and ENABLE + FORCE RLS with the standard policy.
       Alembic does not compare a partial index's predicate — removing
       postgresql_where from the model was checked and produced no diff — so
       the index test below is what pins "WHERE is_active" on both sides.
Why:   A future autogenerated revision must not propose "fixing" the database
       to match a drifted model.
How:   pytest tests/integration/test_dora_v2_002b_schema_parity.py -m integration -v
"""

from __future__ import annotations

import os

import pytest
from sqlalchemy import CheckConstraint, DefaultClause, ForeignKeyConstraint, MetaData, create_engine, text

from src.models import Base
from src.models.dora_contract import DORAContract
from src.models.dora_contract_relationship import DORAContractRelationship
from src.models.tenant import Tenant

# Tenant and DORAContract are imported so the metadata can resolve the foreign
# keys the table declares; the scope hooks exclude both from the comparison.

_TABLE = DORAContractRelationship.__tablename__

_EXPECTED_CHECKS = {
    "ck_dora_contract_relationships_not_self": "CHECK ((child_contract_id <> parent_contract_id))",
    "ck_dora_contract_relationships_type": "CHECK ((relationship_type = 'overarching'::text))",
}
_EXPECTED_MODEL_CHECKS = {
    "ck_dora_contract_relationships_not_self": "child_contract_id <> parent_contract_id",
    "ck_dora_contract_relationships_type": "relationship_type = 'overarching'",
}
_EXPECTED_PRIMARY_KEY = {"dora_contract_relationships_pkey": "PRIMARY KEY (contract_relationship_id)"}
_EXPECTED_FOREIGN_KEYS = {
    "dora_contract_relationships_tenant_id_fkey": "FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id)",
    "fk_dora_contract_relationships_child":
        "FOREIGN KEY (tenant_id, child_contract_id) REFERENCES dora_contracts(tenant_id, contract_id)",
    "fk_dora_contract_relationships_parent":
        "FOREIGN KEY (tenant_id, parent_contract_id) REFERENCES dora_contracts(tenant_id, contract_id)",
}
_EXPECTED_INDEXES = {
    "uq_dora_contract_relationships_one_active_parent":
        "CREATE UNIQUE INDEX uq_dora_contract_relationships_one_active_parent ON public.dora_contract_relationships "
        "USING btree (tenant_id, child_contract_id, relationship_type) WHERE is_active",
    "ix_dora_contract_relationships_tenant_child":
        "CREATE INDEX ix_dora_contract_relationships_tenant_child ON public.dora_contract_relationships "
        "USING btree (tenant_id, child_contract_id)",
    "ix_dora_contract_relationships_tenant_parent":
        "CREATE INDEX ix_dora_contract_relationships_tenant_parent ON public.dora_contract_relationships "
        "USING btree (tenant_id, parent_contract_id)",
}
_EXPECTED_COLUMN_DEFAULTS = {
    "contract_relationship_id": "gen_random_uuid()",
    "is_active": "true",
    "created_at": "now()",
    "updated_at": "now()",
}

_CONSTRAINT_DEFS_SQL = """
SELECT con.conname, pg_get_constraintdef(con.oid)
FROM pg_constraint con
JOIN pg_class rel ON rel.oid = con.conrelid
JOIN pg_namespace ns ON ns.oid = rel.relnamespace
WHERE ns.nspname = 'public' AND rel.relname = %s AND con.contype = %s
"""
_INDEX_DEFS_SQL = """
SELECT indexname, indexdef FROM pg_indexes
WHERE schemaname = 'public' AND tablename = %s AND indexname NOT LIKE '%%_pkey'
"""
_COLUMN_DEFAULTS_SQL = """
SELECT column_name, column_default FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = %s AND column_default IS NOT NULL
"""


def _in_scope_reflected(name, type_, parent_names) -> bool:
    """Alembic include_name hook: reflect only the relationship table."""
    if type_ == "table":
        return name == _TABLE
    return True


def _in_scope_object(obj, name, type_, reflected, compare_to) -> bool:
    """Alembic include_object hook: compare only objects belonging to the relationship table."""
    if type_ == "table":
        return name == _TABLE
    return True


def _scoped_metadata_diff(metadata: MetaData) -> list:
    """Run compare_metadata for the relationship table only, types and server defaults compared, flattened."""
    from alembic.autogenerate import compare_metadata
    from alembic.migration import MigrationContext

    engine = create_engine(os.environ["DATABASE_URL"])
    try:
        with engine.connect() as connection:
            migration_context = MigrationContext.configure(
                connection,
                opts={
                    "compare_type": True,
                    "compare_server_default": True,
                    "include_name": _in_scope_reflected,
                    "include_object": _in_scope_object,
                },
            )
            diffs = compare_metadata(migration_context, metadata)
    finally:
        engine.dispose()
    flat = []
    for group in diffs:
        flat.extend(group if isinstance(group, list) else [group])
    return flat


def _copy(include_relationships: bool = True) -> MetaData:
    """Return a fresh MetaData holding tenants, contracts and (optionally) relationships, for mutation tests."""
    copied = MetaData()
    models = (Tenant, DORAContract, DORAContractRelationship) if include_relationships else (Tenant, DORAContract)
    for model in models:
        model.__table__.to_metadata(copied)
    return copied


def _catalog(conn, sql: str, *params) -> dict[str, str]:
    """Run a two-column (name, definition) catalog query for the relationship table."""
    with conn.transaction():
        return dict(conn.execute(sql, [_TABLE, *params]).fetchall())


# ── Alembic's comparison, scoped, server defaults on ────────────────────────


@pytest.mark.integration
def test_alembic_finds_no_drift_between_the_model_and_the_live_table(db_connection):
    diffs = _scoped_metadata_diff(Base.metadata)
    assert diffs == [], "autogenerate would propose: " + "; ".join(str(d)[:200] for d in diffs)


@pytest.mark.integration
def test_the_scope_filter_is_not_hiding_the_table(db_connection):
    diffs = _scoped_metadata_diff(_copy(include_relationships=False))
    assert {d[1].name for d in diffs if d[0] == "remove_table"} == {_TABLE}


@pytest.mark.integration
def test_server_default_comparison_is_actually_in_effect(db_connection):
    mutated = _copy()
    mutated.tables[_TABLE].c.is_active.server_default = DefaultClause(text("false"))
    diffs = _scoped_metadata_diff(mutated)
    assert [(d[0], d[2], d[3]) for d in diffs] == [("modify_default", _TABLE, "is_active")]


# ── What the comparison cannot see, from the catalogs ───────────────────────


@pytest.mark.integration
def test_check_constraints_are_exactly_what_migration_027_wrote(db_connection):
    assert _catalog(db_connection, _CONSTRAINT_DEFS_SQL, "c") == _EXPECTED_CHECKS
    model_checks = {
        c.name: str(c.sqltext) for c in DORAContractRelationship.__table__.constraints if isinstance(c, CheckConstraint)
    }
    assert model_checks == _EXPECTED_MODEL_CHECKS


@pytest.mark.integration
def test_the_primary_key_and_foreign_keys_are_exactly_what_migration_027_wrote(db_connection):
    assert _catalog(db_connection, _CONSTRAINT_DEFS_SQL, "p") == _EXPECTED_PRIMARY_KEY
    assert _catalog(db_connection, _CONSTRAINT_DEFS_SQL, "f") == _EXPECTED_FOREIGN_KEYS
    model_keys = {c.name for c in DORAContractRelationship.__table__.constraints if isinstance(c, ForeignKeyConstraint)}
    assert model_keys == set(_EXPECTED_FOREIGN_KEYS)


@pytest.mark.integration
def test_no_unique_constraint_exists_only_the_partial_unique_index(db_connection):
    assert _catalog(db_connection, _CONSTRAINT_DEFS_SQL, "u") == {}


@pytest.mark.integration
def test_every_index_including_the_partial_predicate_is_exactly_what_migration_027_wrote(db_connection):
    assert _catalog(db_connection, _INDEX_DEFS_SQL) == _EXPECTED_INDEXES
    model_indexes = {
        ix.name: ([c.name for c in ix.columns], ix.unique, str(ix.dialect_options["postgresql"]["where"]))
        for ix in DORAContractRelationship.__table__.indexes
    }
    assert model_indexes == {
        "uq_dora_contract_relationships_one_active_parent":
            (["tenant_id", "child_contract_id", "relationship_type"], True, "is_active"),
        "ix_dora_contract_relationships_tenant_child": (["tenant_id", "child_contract_id"], False, "None"),
        "ix_dora_contract_relationships_tenant_parent": (["tenant_id", "parent_contract_id"], False, "None"),
    }


@pytest.mark.integration
def test_column_defaults_are_exactly_what_migration_027_wrote(db_connection):
    assert _catalog(db_connection, _COLUMN_DEFAULTS_SQL) == _EXPECTED_COLUMN_DEFAULTS


@pytest.mark.integration
def test_rls_is_enabled_and_forced_with_the_standard_policy(db_connection):
    with db_connection.transaction():
        enabled, forced = db_connection.execute(
            "SELECT relrowsecurity, relforcerowsecurity FROM pg_class WHERE relname = %s", [_TABLE]
        ).fetchone()
        policies = db_connection.execute(
            "SELECT polname, polcmd, pg_get_expr(polqual, polrelid), polwithcheck IS NULL "
            "FROM pg_policy WHERE polrelid = %s::regclass",
            [_TABLE],
        ).fetchall()
    assert (enabled, forced) == (True, True)
    assert policies == [(
        "tenant_isolation_policy", "*",
        "(tenant_id = (current_setting('app.current_tenant_id'::text, true))::uuid)", True,
    )]
