"""compliance_control.py — ORM model and constants for the NIS2 control catalogue.

What:  Defines ComplianceControl, the central table that stores every regulatory
       obligation (NIS2, DORA, CRA, AI Act) the Decision layer reasons over.
       Also defines all authoritative string constants for frameworks, categories,
       entity types, and crosswalk relationships used across Documents 11–13.

Why:   KER-103 requires a schema backbone connecting ingested evidence (Document 10)
       to recommendations (Document 13) via controls. Controls are platform-wide
       data — no RLS and no tenant context is required.

How to run or test:
    pytest tests/unit/models/test_compliance_control.py -v
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, String, Text, func
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.dialects.postgresql import UUID as PostgresUUID
from sqlalchemy.orm import Mapped, mapped_column

from src.models import Base

# ---------------------------------------------------------------------------
# Framework constants — the four regulatory regimes the platform covers.
# Source: PROMPT_doc11_nis2_control_mapping.md §3.5
# ---------------------------------------------------------------------------
FRAMEWORK_NIS2: str = "nis2"
FRAMEWORK_DORA: str = "dora"
FRAMEWORK_CRA: str = "cra"
FRAMEWORK_AI_ACT: str = "ai_act"

# ---------------------------------------------------------------------------
# Category constants — the seven control domains displayed in the Trust Center.
# Source: PROMPT_doc11_nis2_control_mapping.md §3.4 / Trust Center Spec §4
# ---------------------------------------------------------------------------
CATEGORY_GOVERNANCE: str = "governance"
CATEGORY_RISK_MANAGEMENT: str = "risk_management"
CATEGORY_INCIDENT_HANDLING: str = "incident_handling"
CATEGORY_SUPPLY_CHAIN: str = "supply_chain"
CATEGORY_VULNERABILITY: str = "vulnerability"
CATEGORY_AI_OVERSIGHT: str = "ai_oversight"
CATEGORY_OPERATIONAL_RESILIENCE: str = "operational_resilience"

# ---------------------------------------------------------------------------
# Entity type constants — NIS2 entity classification.
# Source: PROMPT_doc11_nis2_control_mapping.md §4.6 (entity_types note)
# ---------------------------------------------------------------------------
ENTITY_ESSENTIAL: str = "essential"
ENTITY_IMPORTANT: str = "important"

# ---------------------------------------------------------------------------
# Crosswalk relationship constants — degree of overlap between two controls.
# Source: PROMPT_doc11_nis2_control_mapping.md §3.6
# ---------------------------------------------------------------------------
RELATIONSHIP_EQUIVALENT: str = "equivalent"
RELATIONSHIP_PARTIAL: str = "partial"
RELATIONSHIP_RELATED: str = "related"


class ComplianceControl(Base):
    """One row per regulatory obligation across all supported frameworks.

    Stores NIS2 articles alongside their DORA, CRA, and AI Act equivalents.
    control_id is generated by uuid.uuid4() in the service layer before INSERT.
    is_active=False marks controls that are retired or superseded and must be
    excluded from coverage calculations. entity_types lists which NIS2 entity
    classifications (essential / important) this obligation applies to, stored
    as a PostgreSQL TEXT[] array.
    """

    __tablename__ = "compliance_controls"

    control_id: Mapped[uuid.UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        primary_key=True,
        comment="Generated by uuid.uuid4() in Python before INSERT",
    )
    framework: Mapped[str] = mapped_column(String(32), nullable=False)
    control_ref: Mapped[str] = mapped_column(String(64), nullable=False)
    category: Mapped[str] = mapped_column(String(64), nullable=False)
    title: Mapped[str] = mapped_column(String(120), nullable=False)
    obligation_text: Mapped[str] = mapped_column(Text, nullable=False)
    entity_types: Mapped[list[str]] = mapped_column(ARRAY(Text), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
