"""control_evidence_link.py — Schema stub linking controls to ingested evidence.

What:  Defines ControlEvidenceLink, the join table that connects a compliance
       control to a context record (ingested piece of evidence). This file
       creates the ORM model and the database table; it writes no data.

Why:   KER-103 AC-3 requires that the schema supports a many-to-many
       control-to-evidence relationship. The table is created here so that
       migration 008 is reversible and the schema is in place before Document 12
       activates it.

Populated by Document 12:
       All data in this table is written by Document 12 (KER-104 /
       src/services/evidence_service.py). Document 12 also applies RLS to this
       table. Document 11 creates the table structure only.

How to run or test:
    pytest tests/unit/models/test_compliance_control.py -v
    (The model is imported and inspected there; no separate test file exists
    for this stub because Document 12 owns the service-layer tests.)
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Float, String, Text
from sqlalchemy.dialects.postgresql import UUID as PostgresUUID
from sqlalchemy.orm import Mapped, mapped_column

from src.models import Base


class ControlEvidenceLink(Base):
    """Join table connecting one compliance control to one ingested context record.

    link_id is generated by uuid.uuid4() in the Document 12 service before INSERT.
    linked_by identifies the actor that created the link — either a user ID or
    the literal string "system" for automated links. relevance_score is a 0.0–1.0
    float set by the Decision layer; it is nullable because manual links may not
    have a computed score. RLS on this table is applied by Document 12.
    """

    __tablename__ = "control_evidence_links"

    link_id: Mapped[uuid.UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        primary_key=True,
        comment="Generated by uuid.uuid4() in Python before INSERT",
    )
    control_id: Mapped[uuid.UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → compliance_controls(control_id)",
    )
    record_id: Mapped[uuid.UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        nullable=False,
        comment="FK → context_records(record_id); table created by Document 10",
    )
    linked_by: Mapped[str] = mapped_column(String(255), nullable=False)
    linked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    relevance_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
