"""control_crosswalk.py — ORM model for cross-framework control mappings.

What:  Defines ControlCrosswalk, which records directional overlap between a
       NIS2 control and its equivalent or related obligation in DORA, CRA, or
       the AI Act. One row per directional pair.

Why:   KER-103 AC-2 requires that when a control overlaps another regime, a
       crosswalk link to the equivalent is persisted. This enables the Trust
       Center to show coverage across multiple frameworks from a single set of
       evidence.

How to run or test:
    pytest tests/unit/services/test_control_service.py -v -k crosswalk
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, String, Text, func
from sqlalchemy.dialects.postgresql import UUID as PostgresUUID
from sqlalchemy.orm import Mapped, mapped_column

from src.models import Base


class ControlCrosswalk(Base):
    """A directional link from one framework's control to an equivalent in another.

    crosswalk_id is generated by uuid.uuid4() in the service layer before INSERT.
    relationship describes the degree of overlap: equivalent means the two
    obligations are substantively the same; partial means one is a subset of the
    other; related means they address the same domain but differ in scope.
    note carries a human-readable explanation of the mapping when the relationship
    is not self-evident.
    """

    __tablename__ = "control_crosswalks"

    crosswalk_id: Mapped[uuid.UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        primary_key=True,
        comment="Generated by uuid.uuid4() in Python before INSERT",
    )
    source_control_id: Mapped[uuid.UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="FK → compliance_controls(control_id)",
    )
    target_control_id: Mapped[uuid.UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        nullable=False,
        comment="FK → compliance_controls(control_id)",
    )
    relationship: Mapped[str] = mapped_column(String(32), nullable=False)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
