"""The per-tenant retrieval bias vector — a company's learned search calibration.

Plain-English summary
---------------------
As compliance engineers at a customer correct the AI's control recommendations
(their "overrides"), Kerno learns the direction in which that company's correct
answers tend to sit. It stores that learning as a single vector of numbers — the
"retrieval bias vector" — one per tenant. Every night the batch job recomputes
it from the latest overrides, and every search the company runs is nudged by it
so the results match how that specific company thinks.

This file defines where that vector lives in the database. There is exactly one
row per tenant: the row IS the company's accumulated calibration. If a tenant has
no row yet, it simply hasn't been calibrated and searches run unbiased.

The vector width is fixed at the embedding model's dimensionality (pulled from
config, never hard-coded here) so the bias vector and the stored embeddings can
be compared directly in the calibrated similarity query. (KER-114,
LEARNING_PIPELINE_SPEC.md Section 5.)

How to run or test
------------------
Model files have no executable logic of their own. Syntax-check with:

    python -c "from src.models.retrieval_bias import RetrievalBias; print('OK')"

(Requires pgvector and SQLAlchemy installed.)
Integration tests that exercise this model live in
tests/integration/test_override_to_bias_pipeline.py.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import DateTime, ForeignKey, Integer, text
from sqlalchemy.dialects.postgresql import UUID as PostgresUUID
from sqlalchemy.orm import Mapped, mapped_column

from config.constants import EMBEDDING_DIMENSION
from src.models import Base


class RetrievalBias(Base):
    """One tenant's learned search calibration, stored as a single vector row.

    Created or refreshed by the nightly recalculation batch (KER-114). Exactly
    one row may exist per tenant, enforced by a unique constraint on
    ``tenant_id`` so the batch can update-in-place rather than accumulate rows.
    """

    __tablename__ = "retrieval_bias"

    # Surrogate primary key for this calibration row, generated by the database.
    id: Mapped[uuid.UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        nullable=False,
    )

    # Which tenant this calibration belongs to. Unique + indexed: one row per
    # tenant, and fast lookup by tenant during every biased search.
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        ForeignKey("tenants.tenant_id"),
        nullable=False,
        unique=True,
        index=True,
    )

    # The learned calibration itself. Same width as the stored embeddings so the
    # two can be compared in the similarity query. Width comes from config.
    bias_vector: Mapped[list[float]] = mapped_column(
        Vector(EMBEDDING_DIMENSION),
        nullable=False,
    )

    # How many overrides contributed to the current vector — used to tell whether
    # the tenant has crossed the calibration threshold (see config.constants).
    override_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        server_default=text("0"),
        default=0,
    )

    # When the nightly batch last refreshed this vector.
    last_recalculated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        nullable=False,
    )

    # When this calibration row was first created.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        nullable=False,
    )

    def __repr__(self) -> str:
        """Short, safe summary for logs and test output (no vector contents)."""
        return (
            f"<RetrievalBias tenant_id={self.tenant_id!s} "
            f"override_count={self.override_count}>"
        )
